import '@/src/styles/app.scss'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    )
}


// import '@/src/styles/app.scss'
// import { SessionProvider } from "next-auth/react"
// import type { AppProps } from 'next/app'

// export default function App({ Component, pageProps: { session, ...pageProps } }: AppProps) {
//   return <SessionProvider session={session}>
//     <Component {...pageProps} />
//   </SessionProvider>
// }

